### PR TITLE
Simplified build of Java examples by migrating from Ant to Gradle

### PR DESCRIPTION
**Pull request by geoand**
Made execution of the Java examples easier by swapping the existing Ant build script with Gradle.
As explained in the Readme, all one needs to have installed is a JDK 6 or higher, nothing else, as opposed to the existing code-base, where an Ant installation is required. 

Note that the dependencies used in the existing code where not changed - same versions are used by the new script.

### CODE REVIEW

**Comment by josiahcarlson** [comment]
I'm sorry I haven't gotten to this yet, I'll probably be merging your changes later tonight or in the next couple days. Thank you for your work :)

**Comment by geoand** [comment]
Thank you for your time and effort on the book! It's great!

**Comment by josiahcarlson** [comment]
I'm glad you're enjoying the book. Thank you again for the patch :)

**Comment by geoand** [comment]
Your most welcome!

Thank you for your great work!

Regards,
George

**Pull request merged**
